### ISSUE TITLE
1.18.2: Incompatible with MemoryLeakFix

### ISSUE THREAD

**Issue by Roadhog360** [DawnTeamMC/DawnAPI#29]
### What happened?

When installing Dawn and [MemoryLeakFix - v0.3.5](https://modrinth.com/mod/memoryleakfix/version/v0.3.5) together, Dawn throws an error that prevents the game from starting.

Sorry if 1.18.2 isn't supported, since 1.19 has been so negatively received especially after reports were revealed, I'm not sure if "latest" requires latest version of the mod on latest version, or just the latest version of the mod for the version I use.
A handful of the mods I use haven't updated probably because of the backlash, which is an issue "no chat reports" can't fix.

That being said, if 1.18.2 is supported, thank you. Please let me know if I missed anything.

### Fabric API version

0.57.0-1.18.2 API on Fabric 0.14.8-1.18.2

### Relevant log output

```shell
Mixin apply for mod dawn failed dawn_mod.mixins.json:WorldgenProviderAccessor from mod dawn -> net.minecraft.class_5475: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching writeRegistryEntries(Lnet/minecraft/class_2408;Ljava/nio/file/Path;Lnet/minecraft/class_5455;Lcom/mojang/serialization/DynamicOps;Lnet/minecraft/class_5455$class_5456;)V in net/minecraft/class_5475 for dawn_mod.mixins.json:WorldgenProviderAccessor from mod dawn->@Invoker[METHOD_PROXY]::dawn$invokeWriteRegistryEntries(Lnet/minecraft/class_2408;Ljava/nio/file/Path;Lnet/minecraft/class_5455;Lcom/mojang/serialization/DynamicOps;Lnet/minecraft/class_5455$class_5456;)V [INJECT Applicator Phase -> dawn_mod.mixins.json:WorldgenProviderAccessor from mod dawn -> Apply Accessors ->  -> Locate -> dawn_mod.mixins.json:WorldgenProviderAccessor from mod dawn->@Invoker[METHOD_PROXY]::dawn$invokeWriteRegistryEntries(Lnet/minecraft/class_2408;Ljava/nio/file/Path;Lnet/minecraft/class_5455;Lcom/mojang/serialization/DynamicOps;Lnet/minecraft/class_5455$class_5456;)V]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching writeRegistryEntries(Lnet/minecraft/class_2408;Ljava/nio/file/Path;Lnet/minecraft/class_5455;Lcom/mojang/serialization/DynamicOps;Lnet/minecraft/class_5455$class_5456;)V in net/minecraft/class_5475 for dawn_mod.mixins.json:WorldgenProviderAccessor from mod dawn->@Invoker[METHOD_PROXY]::dawn$invokeWriteRegistryEntries(Lnet/minecraft/class_2408;Ljava/nio/file/Path;Lnet/minecraft/class_5455;Lcom/mojang/serialization/DynamicOps;Lnet/minecraft/class_5455$class_5456;)V [INJECT Applicator Phase -> dawn_mod.mixins.json:WorldgenProviderAccessor from mod dawn -> Apply Accessors ->  -> Locate -> dawn_mod.mixins.json:WorldgenProviderAccessor from mod dawn->@Invoker[METHOD_PROXY]::dawn$invokeWriteRegistryEntries(Lnet/minecraft/class_2408;Ljava/nio/file/Path;Lnet/minecraft/class_5455;Lcom/mojang/serialization/DynamicOps;Lnet/minecraft/class_5455$class_5456;)V]
	at org.spongepowered.asm.mixin.gen.InvokerInfo.findTargetMethod(InvokerInfo.java:119)
	at org.spongepowered.asm.mixin.gen.InvokerInfo.locate(InvokerInfo.java:102)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1412)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1061)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:398)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:96)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.audit(MixinProcessor.java:254)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.audit(MixinTransformer.java:171)
	at org.spongepowered.asm.mixin.MixinEnvironment.audit(MixinEnvironment.java:1425)
	at ca.fxco.memoryleakfix.MemoryLeakFix.forceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFix.java:25)
	at net.minecraft.client.main.Main.redirect$cao000$loadAllMixinsThenShouldRenderAsync(Main.java:525)
	at net.minecraft.client.main.Main.main(Main.java:212)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
05:21:28.918
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5475 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5475 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:96)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.audit(MixinProcessor.java:254)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.audit(MixinTransformer.java:171)
	at org.spongepowered.asm.mixin.MixinEnvironment.audit(MixinEnvironment.java:1425)
	at ca.fxco.memoryleakfix.MemoryLeakFix.forceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFix.java:25)
	at net.minecraft.client.main.Main.redirect$cao000$loadAllMixinsThenShouldRenderAsync(Main.java:525)
	at net.minecraft.client.main.Main.main(Main.java:212)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 16 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [dawn_mod.mixins.json:WorldgenProviderAccessor from mod dawn] from phase [DEFAULT] in config [dawn_mod.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 19 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching writeRegistryEntries(Lnet/minecraft/class_2408;Ljava/nio/file/Path;Lnet/minecraft/class_5455;Lcom/mojang/serialization/DynamicOps;Lnet/minecraft/class_5455$class_5456;)V in net/minecraft/class_5475 for dawn_mod.mixins.json:WorldgenProviderAccessor from mod dawn->@Invoker[METHOD_PROXY]::dawn$invokeWriteRegistryEntries(Lnet/minecraft/class_2408;Ljava/nio/file/Path;Lnet/minecraft/class_5455;Lcom/mojang/serialization/DynamicOps;Lnet/minecraft/class_5455$class_5456;)V [INJECT Applicator Phase -> dawn_mod.mixins.json:WorldgenProviderAccessor from mod dawn -> Apply Accessors ->  -> Locate -> dawn_mod.mixins.json:WorldgenProviderAccessor from mod dawn->@Invoker[METHOD_PROXY]::dawn$invokeWriteRegistryEntries(Lnet/minecraft/class_2408;Ljava/nio/file/Path;Lnet/minecraft/class_5455;Lcom/mojang/serialization/DynamicOps;Lnet/minecraft/class_5455$class_5456;)V]
	at org.spongepowered.asm.mixin.gen.InvokerInfo.findTargetMethod(InvokerInfo.java:119)
	at org.spongepowered.asm.mixin.gen.InvokerInfo.locate(InvokerInfo.java:102)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1412)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1061)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:398)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 19 more
```

**Comment by Hugman76** [comment]
Have you tried booting up the game with the Dawn API alone? What version of the Dawn API are your using?

**Comment by Roadhog360** [comment]
Dawn API is on 3.3.2.
I assumed no other mods were tangled up in this but forgot that Fabric errors can hide a lot more than Forge errors due to the nature of Mixins.
I will do more testing when I get home.

**Comment by Hugman76** [comment]
### Thanks for the report!
However, this report is invalid. This issue has already been fixed in a more recent version of the mod. (v3.4.0)

**Comment by Roadhog360** [comment]
3.3.2 is the most recent version available on Modrinth for 1.18.2, I opened the Modrinth page when you asked just to check. 3.4.0 is for 1.19. I cannot update to a version for 1.19 on 1.18.2.
@Hugman76

**Comment by Hugman76** [comment]
Huh, well I won't apply any changes to older versions anyway, sorry.

**Comment by Roadhog360** [comment]
Well that's a shame, can I make a build to apply the fix myself for my pack?

**Comment by Hugman76** [comment]
Of course! Feel free to fork any of my projects as long as you don't distribute it
